### ISSUE TITLE
Can this h.264 encode on the V3?

### ISSUE THREAD

**Issue by jonsmirl** [aodzip/cedar#1]
Does this driver work to h.264 encode on the V3/S3/etc? Do you have an example of user space code to do the encoding?

**Comment by aodzip** [comment]
Yes，I have tested YUV420P to H.264 Encode and MJPEG to YUV Decode. Including video scale.
The user space lib when I test was close source Allwinner lib. It is more different than “opensource” Allwinner media-codec lib. I just “can’t ” provide a user space demo. 
But I think the driver API is compatible with open source version lib. You can try it out. Or using leaked Allwinner lib.

**Comment by jonsmirl** [comment]
The binary cedar libs are not "leaked" they are provided in the V3/S3 SDK so that people designing boards with the chip can write and distribute software. The binaries are free to redistribute.

This is what you used, right?
jonsmirl@ares:~/foo/bin$ ls /home/jonsmirl/aosp/lichee-s3/s3linux/prebuild/libs
libaw_net.so  libcdc_base.so    libcdc_sdecoder.so  libcdc_vd_h264.so  libcdc_vdecoder.so  libcdc_vencoder.so  libmediaplayer.so  zeta.in
libcamera.so  libcdc_memory.so  libcdc_vd_avs.so    libcdc_vd_h265.so  libcdc_ve.so        libcutils.so        librecorder.so

**Comment by aodzip** [comment]
Yes，the filename is right.

**Comment by jonsmirl** [comment]
Those files are free to redistribute. If you couldn't redistribute them you could never ship software to a customer.  

You can't redistribute the source to those files, but Allwinner has never released the source so that question doesn't matter.

**Comment by aodzip** [comment]
I think you are right.  But the demo I used is another company’s factory quality inspection software. Later maybe I can make some free demo.

**Comment by jonsmirl** [comment]
Are you using the HQEmbed board?`

**Comment by aodzip** [comment]
No. I test my driver using a board designed by my self.
