### ISSUE TITLE
Issues with cedar on F1C100S (Bittboy/PocketGo)

### ISSUE THREAD

**Issue by gameblabla** [aodzip/cedar#4]
Hello,
i had managed to compile your cedar kernel drivers in my own branch here for the bittboy/pocketgo kernel (4.14) :
https://github.com/gameblabla/kernel/commits/master

The PocketGo/Bittboy use an F1C100S (ARMv5) with only 32MB of RAM. So i couldn't allocate 32MB for the CMA.
Tried 8MB at first but didn't work. 16MB wouldn't work and 20MB would error out.
So i set it to 12MB right now but it still makes no difference.

The cedar_dev kernel module does appear in /dev. However, i am unable to use it for either encoding or decoding.
[dmesg.txt](https://github.com/aodzip/cedar/files/5539726/dmesg.txt)

I tried with CedarX Player found here : https://github.com/iainb/CedarXPlayerTest
Unfortunately, no luck here. It's possible it tries to allocate too much memory...
[cdx_player_log.txt](https://github.com/aodzip/cedar/files/5539665/cdx_player_log.txt)

I then tried ffmpeg with omx enabled as you suggested. I tried a very small video (2s) but it seems to hang on an error.
`ffmpeg -i ex.mp4 -codec:v h264_omx -b:v 2048k final.mp4 &> ./final.txt`

[omx_errors.txt](https://github.com/aodzip/cedar/files/5539732/omx_errors.txt)
```
debug  : cedarc <VeSetSpeed:1559>: *** set ve freq to 300 Mhz ***
debug  : cedarc <VeInitialize:1198>: ve init ok

debug  : ionAlloc <__GetIonMemOpsS:985>:*** get __GetIonMemOpsS ***
debug  : ionAlloc <ion_alloc_open:134>:begin ion_alloc_open 

debug  : omx_venc <init_h264_param:2820>:profile-venc=66, profile-omx=1, frame_rate:1966080, bit_rate:2048000, idr:12, eColorFormat:00000013

debug  : omx_venc <init_h264_param:2946>:Enable VBR. QpMin: 20. QpMax: 45. Bitrate: 2048000.
debug  : cedarc <determineVencColorFormat:167>:color format: VENC_PIXEL_YUV420P/I420
debug  : omx_venc <openVencDriver:3184>:omx_venc base_config info: src_wxh:320x240, dis_wxh:320x240, stride:320

debug  : ionAlloc <__GetIonMemOpsS:985>:*** get __GetIonMemOpsS ***
debug  : omx_venc <openVencDriver:3221>:AVC 4 byte interleave nalu Disable.
debug  : cedarc <VideoEncInit:195>: (f:VideoEncInit, l:195)
debug  : cedarc <VideoEncInit:210>: (f:VideoEncInit, l:210)
error  : ionAlloc <ion_alloc_palloc:335>:[40;31mION_[h264_omx @ 0x937a0] OMX error 80001009
```

Not sure what's going on...
I'm using the "toolchain-sunxi-arm9-glibc" libraries for my architecture.
https://github.com/bittboy/rootfs/commit/c888612414092f20922d7da9721cd73d252e2167

Any ideas ? Thank you.

**Comment by aodzip** [comment]
最近买了100s，过两天测试一下
